### PR TITLE
Math-Magicians: Router

### PR DESCRIPTION
**Pull request by julzedz**
In this milestone, I completed the math magician website by:

- Setting up React Routers for the different pages.
- Adding styling to the pages.

### CODE REVIEW

**Review by mmsesay — CHANGES_REQUESTED** [review]
Hi @julzedz, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 - Good Readme :heavy_check_mark: 
 - No linter error :heavy_check_mark: 
 - Good PR title :heavy_check_mark: 
 - Good PR summary : heavy_check_mark:  


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Fixing the compile error. This occurs immediately after the app starts.

|    Screenshot of Error |
:---------------------:|
Screen Shot 2022-11-04 at 8 42 08 PM |

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julzedz** [comment]
Hi @mmsesay, your review starts with "You can **also** consider". 
Makes me wonder if something was mistakenly left out cuz the review seems very vague, I just ran the app and it's running and my Quote.js file starts with a capital letter unlike in the screenshot you sent.
Can you kindly assist with clearer suggestions? Thanks.

**Comment by mmsesay** [comment]
Hi @julzedz, Thanks for the quick reply. I ran your project from the `router` branch that is associated with this PR. Under pages, the quote file starts with a lowercase letter. Are you running from the `router` branch?

**Comment by julzedz** [comment]
Yes, I am running from the router branch, and under the pages folder, my quote file starts with a capital letter. Can I call you on zoom?

**Comment by mmsesay** [comment]
Git always caches some files. Running ` git rm --cached -r .` will clear all cached files and the new staged and committed files will replace the ones in the remote repo.

I hope this will help going forward.

**Review by jaflih — APPROVED** [review]
Hi @julzedz , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights

Good Readme ✔️
No linter error ✔️
Good PR title ✔️
Good PR summary ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @jaflih in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
